server:
  port: 8081

spring:
  application:
    name: habits-service
  cloud:
    gcp:
      datastore:
        enabled: true
        project-id: macro-scion-300810
  main:
    allow-bean-definition-overriding: true
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
