swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: macro-scion-300810.appspot.com
basePath: /v1
schemes:
  - https
paths:
  /habits:
    get:
      summary: Returns a list of habits.
      operationId: ListAllHabits
      description: Retorna todos os habitos dos usuarios.
      produces:
        - application/json
      responses:
        200:
          description: OK

