apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: accounts-service-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
      - name: accounts-service
        image: raphaelinacio/accounts-service:latest
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: accounts-service