runtime: java11
service: habits-service
#env: flex
#runtime_config:
#  jdk: openjdk11
##env_variables:
##  SPRING_PROFILES_ACTIVE: "gcp,mysql"
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
#manual_scaling:
#  instances: 1